// This file is generated by rust-protobuf 2.11.0. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![cfg_attr(rustfmt, rustfmt_skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unsafe_code)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `one_acc_smry_rep.proto`

use protobuf::Message as Message_imported_for_functions;
use protobuf::ProtobufEnum as ProtobufEnum_imported_for_functions;

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_11_0;

#[derive(PartialEq,Clone,Default)]
pub struct OneAccountView {
    // message fields
    pub as_on_month: i64,
    pub account_id: ::std::string::String,
    pub currency: ::std::string::String,
    pub balance_ccy: f64,
    pub balance_hcy: f64,
    pub int_rate: f32,
    pub acr_int_amt_ccy: f64,
    pub acr_int_amt_hcy: f64,
    pub ftp_method: ::std::string::String,
    pub base_rate_curve_id: i32,
    pub rate_flag: ::std::string::String,
    pub adj_codes: ::std::vec::Vec<i32>,
    pub val_dt: i64,
    pub open_dt: i64,
    pub mat_dt: i64,
    pub lst_repricing_dt: i64,
    pub rep_freq: ::std::string::String,
    pub cust_agg_bal: f64,
    pub day_count_basis: ::std::string::String,
    pub base_rate: f32,
    pub adj_rates: ::std::vec::Vec<f32>,
    pub ftp_rate: f32,
    pub lock_spread: f32,
    pub ftp_amt_ccy: f64,
    pub ftp_amt_hcy: f64,
    pub a_or_l: ::std::string::String,
    pub dim1: ::std::string::String,
    pub dim2: ::std::string::String,
    pub dim3: ::std::string::String,
    pub dim4: ::std::string::String,
    pub customer_id: ::std::string::String,
    pub rl1: ::std::string::String,
    pub rl2: ::std::string::String,
    pub rl3: ::std::string::String,
    pub calc_ftp_rate: f32,
    pub calc_lock_spread: f32,
    pub bc_as_on_rule: i64,
    pub tenor_start_date_rule: i64,
    pub tenor_end_date_rule: i64,
    pub bc_as_on_applied: i64,
    pub tenor_start_date_applied: i64,
    pub tenor_end_date_applied: i64,
    pub gl_code: ::std::string::String,
    pub prod_code: ::std::string::String,
    pub div_code: ::std::string::String,
    pub mis_code_1: ::std::string::String,
    pub mis_code_2: ::std::string::String,
    pub mis_code_3: ::std::string::String,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a OneAccountView {
    fn default() -> &'a OneAccountView {
        <OneAccountView as ::protobuf::Message>::default_instance()
    }
}

impl OneAccountView {
    pub fn new() -> OneAccountView {
        ::std::default::Default::default()
    }

    // int64 as_on_month = 1;


    pub fn get_as_on_month(&self) -> i64 {
        self.as_on_month
    }
    pub fn clear_as_on_month(&mut self) {
        self.as_on_month = 0;
    }

    // Param is passed by value, moved
    pub fn set_as_on_month(&mut self, v: i64) {
        self.as_on_month = v;
    }

    // string account_id = 2;


    pub fn get_account_id(&self) -> &str {
        &self.account_id
    }
    pub fn clear_account_id(&mut self) {
        self.account_id.clear();
    }

    // Param is passed by value, moved
    pub fn set_account_id(&mut self, v: ::std::string::String) {
        self.account_id = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_account_id(&mut self) -> &mut ::std::string::String {
        &mut self.account_id
    }

    // Take field
    pub fn take_account_id(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.account_id, ::std::string::String::new())
    }

    // string currency = 3;


    pub fn get_currency(&self) -> &str {
        &self.currency
    }
    pub fn clear_currency(&mut self) {
        self.currency.clear();
    }

    // Param is passed by value, moved
    pub fn set_currency(&mut self, v: ::std::string::String) {
        self.currency = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_currency(&mut self) -> &mut ::std::string::String {
        &mut self.currency
    }

    // Take field
    pub fn take_currency(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.currency, ::std::string::String::new())
    }

    // double balance_ccy = 4;


    pub fn get_balance_ccy(&self) -> f64 {
        self.balance_ccy
    }
    pub fn clear_balance_ccy(&mut self) {
        self.balance_ccy = 0.;
    }

    // Param is passed by value, moved
    pub fn set_balance_ccy(&mut self, v: f64) {
        self.balance_ccy = v;
    }

    // double balance_hcy = 5;


    pub fn get_balance_hcy(&self) -> f64 {
        self.balance_hcy
    }
    pub fn clear_balance_hcy(&mut self) {
        self.balance_hcy = 0.;
    }

    // Param is passed by value, moved
    pub fn set_balance_hcy(&mut self, v: f64) {
        self.balance_hcy = v;
    }

    // float int_rate = 6;


    pub fn get_int_rate(&self) -> f32 {
        self.int_rate
    }
    pub fn clear_int_rate(&mut self) {
        self.int_rate = 0.;
    }

    // Param is passed by value, moved
    pub fn set_int_rate(&mut self, v: f32) {
        self.int_rate = v;
    }

    // double acr_int_amt_ccy = 7;


    pub fn get_acr_int_amt_ccy(&self) -> f64 {
        self.acr_int_amt_ccy
    }
    pub fn clear_acr_int_amt_ccy(&mut self) {
        self.acr_int_amt_ccy = 0.;
    }

    // Param is passed by value, moved
    pub fn set_acr_int_amt_ccy(&mut self, v: f64) {
        self.acr_int_amt_ccy = v;
    }

    // double acr_int_amt_hcy = 8;


    pub fn get_acr_int_amt_hcy(&self) -> f64 {
        self.acr_int_amt_hcy
    }
    pub fn clear_acr_int_amt_hcy(&mut self) {
        self.acr_int_amt_hcy = 0.;
    }

    // Param is passed by value, moved
    pub fn set_acr_int_amt_hcy(&mut self, v: f64) {
        self.acr_int_amt_hcy = v;
    }

    // string ftp_method = 9;


    pub fn get_ftp_method(&self) -> &str {
        &self.ftp_method
    }
    pub fn clear_ftp_method(&mut self) {
        self.ftp_method.clear();
    }

    // Param is passed by value, moved
    pub fn set_ftp_method(&mut self, v: ::std::string::String) {
        self.ftp_method = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_ftp_method(&mut self) -> &mut ::std::string::String {
        &mut self.ftp_method
    }

    // Take field
    pub fn take_ftp_method(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.ftp_method, ::std::string::String::new())
    }

    // int32 base_rate_curve_id = 10;


    pub fn get_base_rate_curve_id(&self) -> i32 {
        self.base_rate_curve_id
    }
    pub fn clear_base_rate_curve_id(&mut self) {
        self.base_rate_curve_id = 0;
    }

    // Param is passed by value, moved
    pub fn set_base_rate_curve_id(&mut self, v: i32) {
        self.base_rate_curve_id = v;
    }

    // string rate_flag = 11;


    pub fn get_rate_flag(&self) -> &str {
        &self.rate_flag
    }
    pub fn clear_rate_flag(&mut self) {
        self.rate_flag.clear();
    }

    // Param is passed by value, moved
    pub fn set_rate_flag(&mut self, v: ::std::string::String) {
        self.rate_flag = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_rate_flag(&mut self) -> &mut ::std::string::String {
        &mut self.rate_flag
    }

    // Take field
    pub fn take_rate_flag(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.rate_flag, ::std::string::String::new())
    }

    // repeated int32 adj_codes = 12;


    pub fn get_adj_codes(&self) -> &[i32] {
        &self.adj_codes
    }
    pub fn clear_adj_codes(&mut self) {
        self.adj_codes.clear();
    }

    // Param is passed by value, moved
    pub fn set_adj_codes(&mut self, v: ::std::vec::Vec<i32>) {
        self.adj_codes = v;
    }

    // Mutable pointer to the field.
    pub fn mut_adj_codes(&mut self) -> &mut ::std::vec::Vec<i32> {
        &mut self.adj_codes
    }

    // Take field
    pub fn take_adj_codes(&mut self) -> ::std::vec::Vec<i32> {
        ::std::mem::replace(&mut self.adj_codes, ::std::vec::Vec::new())
    }

    // int64 val_dt = 13;


    pub fn get_val_dt(&self) -> i64 {
        self.val_dt
    }
    pub fn clear_val_dt(&mut self) {
        self.val_dt = 0;
    }

    // Param is passed by value, moved
    pub fn set_val_dt(&mut self, v: i64) {
        self.val_dt = v;
    }

    // int64 open_dt = 14;


    pub fn get_open_dt(&self) -> i64 {
        self.open_dt
    }
    pub fn clear_open_dt(&mut self) {
        self.open_dt = 0;
    }

    // Param is passed by value, moved
    pub fn set_open_dt(&mut self, v: i64) {
        self.open_dt = v;
    }

    // int64 mat_dt = 15;


    pub fn get_mat_dt(&self) -> i64 {
        self.mat_dt
    }
    pub fn clear_mat_dt(&mut self) {
        self.mat_dt = 0;
    }

    // Param is passed by value, moved
    pub fn set_mat_dt(&mut self, v: i64) {
        self.mat_dt = v;
    }

    // int64 lst_repricing_dt = 16;


    pub fn get_lst_repricing_dt(&self) -> i64 {
        self.lst_repricing_dt
    }
    pub fn clear_lst_repricing_dt(&mut self) {
        self.lst_repricing_dt = 0;
    }

    // Param is passed by value, moved
    pub fn set_lst_repricing_dt(&mut self, v: i64) {
        self.lst_repricing_dt = v;
    }

    // string rep_freq = 17;


    pub fn get_rep_freq(&self) -> &str {
        &self.rep_freq
    }
    pub fn clear_rep_freq(&mut self) {
        self.rep_freq.clear();
    }

    // Param is passed by value, moved
    pub fn set_rep_freq(&mut self, v: ::std::string::String) {
        self.rep_freq = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_rep_freq(&mut self) -> &mut ::std::string::String {
        &mut self.rep_freq
    }

    // Take field
    pub fn take_rep_freq(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.rep_freq, ::std::string::String::new())
    }

    // double cust_agg_bal = 18;


    pub fn get_cust_agg_bal(&self) -> f64 {
        self.cust_agg_bal
    }
    pub fn clear_cust_agg_bal(&mut self) {
        self.cust_agg_bal = 0.;
    }

    // Param is passed by value, moved
    pub fn set_cust_agg_bal(&mut self, v: f64) {
        self.cust_agg_bal = v;
    }

    // string day_count_basis = 19;


    pub fn get_day_count_basis(&self) -> &str {
        &self.day_count_basis
    }
    pub fn clear_day_count_basis(&mut self) {
        self.day_count_basis.clear();
    }

    // Param is passed by value, moved
    pub fn set_day_count_basis(&mut self, v: ::std::string::String) {
        self.day_count_basis = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_day_count_basis(&mut self) -> &mut ::std::string::String {
        &mut self.day_count_basis
    }

    // Take field
    pub fn take_day_count_basis(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.day_count_basis, ::std::string::String::new())
    }

    // float base_rate = 20;


    pub fn get_base_rate(&self) -> f32 {
        self.base_rate
    }
    pub fn clear_base_rate(&mut self) {
        self.base_rate = 0.;
    }

    // Param is passed by value, moved
    pub fn set_base_rate(&mut self, v: f32) {
        self.base_rate = v;
    }

    // repeated float adj_rates = 21;


    pub fn get_adj_rates(&self) -> &[f32] {
        &self.adj_rates
    }
    pub fn clear_adj_rates(&mut self) {
        self.adj_rates.clear();
    }

    // Param is passed by value, moved
    pub fn set_adj_rates(&mut self, v: ::std::vec::Vec<f32>) {
        self.adj_rates = v;
    }

    // Mutable pointer to the field.
    pub fn mut_adj_rates(&mut self) -> &mut ::std::vec::Vec<f32> {
        &mut self.adj_rates
    }

    // Take field
    pub fn take_adj_rates(&mut self) -> ::std::vec::Vec<f32> {
        ::std::mem::replace(&mut self.adj_rates, ::std::vec::Vec::new())
    }

    // float ftp_rate = 22;


    pub fn get_ftp_rate(&self) -> f32 {
        self.ftp_rate
    }
    pub fn clear_ftp_rate(&mut self) {
        self.ftp_rate = 0.;
    }

    // Param is passed by value, moved
    pub fn set_ftp_rate(&mut self, v: f32) {
        self.ftp_rate = v;
    }

    // float lock_spread = 23;


    pub fn get_lock_spread(&self) -> f32 {
        self.lock_spread
    }
    pub fn clear_lock_spread(&mut self) {
        self.lock_spread = 0.;
    }

    // Param is passed by value, moved
    pub fn set_lock_spread(&mut self, v: f32) {
        self.lock_spread = v;
    }

    // double ftp_amt_ccy = 24;


    pub fn get_ftp_amt_ccy(&self) -> f64 {
        self.ftp_amt_ccy
    }
    pub fn clear_ftp_amt_ccy(&mut self) {
        self.ftp_amt_ccy = 0.;
    }

    // Param is passed by value, moved
    pub fn set_ftp_amt_ccy(&mut self, v: f64) {
        self.ftp_amt_ccy = v;
    }

    // double ftp_amt_hcy = 25;


    pub fn get_ftp_amt_hcy(&self) -> f64 {
        self.ftp_amt_hcy
    }
    pub fn clear_ftp_amt_hcy(&mut self) {
        self.ftp_amt_hcy = 0.;
    }

    // Param is passed by value, moved
    pub fn set_ftp_amt_hcy(&mut self, v: f64) {
        self.ftp_amt_hcy = v;
    }

    // string a_or_l = 26;


    pub fn get_a_or_l(&self) -> &str {
        &self.a_or_l
    }
    pub fn clear_a_or_l(&mut self) {
        self.a_or_l.clear();
    }

    // Param is passed by value, moved
    pub fn set_a_or_l(&mut self, v: ::std::string::String) {
        self.a_or_l = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_a_or_l(&mut self) -> &mut ::std::string::String {
        &mut self.a_or_l
    }

    // Take field
    pub fn take_a_or_l(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.a_or_l, ::std::string::String::new())
    }

    // string dim1 = 27;


    pub fn get_dim1(&self) -> &str {
        &self.dim1
    }
    pub fn clear_dim1(&mut self) {
        self.dim1.clear();
    }

    // Param is passed by value, moved
    pub fn set_dim1(&mut self, v: ::std::string::String) {
        self.dim1 = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_dim1(&mut self) -> &mut ::std::string::String {
        &mut self.dim1
    }

    // Take field
    pub fn take_dim1(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.dim1, ::std::string::String::new())
    }

    // string dim2 = 28;


    pub fn get_dim2(&self) -> &str {
        &self.dim2
    }
    pub fn clear_dim2(&mut self) {
        self.dim2.clear();
    }

    // Param is passed by value, moved
    pub fn set_dim2(&mut self, v: ::std::string::String) {
        self.dim2 = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_dim2(&mut self) -> &mut ::std::string::String {
        &mut self.dim2
    }

    // Take field
    pub fn take_dim2(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.dim2, ::std::string::String::new())
    }

    // string dim3 = 29;


    pub fn get_dim3(&self) -> &str {
        &self.dim3
    }
    pub fn clear_dim3(&mut self) {
        self.dim3.clear();
    }

    // Param is passed by value, moved
    pub fn set_dim3(&mut self, v: ::std::string::String) {
        self.dim3 = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_dim3(&mut self) -> &mut ::std::string::String {
        &mut self.dim3
    }

    // Take field
    pub fn take_dim3(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.dim3, ::std::string::String::new())
    }

    // string dim4 = 30;


    pub fn get_dim4(&self) -> &str {
        &self.dim4
    }
    pub fn clear_dim4(&mut self) {
        self.dim4.clear();
    }

    // Param is passed by value, moved
    pub fn set_dim4(&mut self, v: ::std::string::String) {
        self.dim4 = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_dim4(&mut self) -> &mut ::std::string::String {
        &mut self.dim4
    }

    // Take field
    pub fn take_dim4(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.dim4, ::std::string::String::new())
    }

    // string customer_id = 31;


    pub fn get_customer_id(&self) -> &str {
        &self.customer_id
    }
    pub fn clear_customer_id(&mut self) {
        self.customer_id.clear();
    }

    // Param is passed by value, moved
    pub fn set_customer_id(&mut self, v: ::std::string::String) {
        self.customer_id = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_customer_id(&mut self) -> &mut ::std::string::String {
        &mut self.customer_id
    }

    // Take field
    pub fn take_customer_id(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.customer_id, ::std::string::String::new())
    }

    // string rl1 = 32;


    pub fn get_rl1(&self) -> &str {
        &self.rl1
    }
    pub fn clear_rl1(&mut self) {
        self.rl1.clear();
    }

    // Param is passed by value, moved
    pub fn set_rl1(&mut self, v: ::std::string::String) {
        self.rl1 = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_rl1(&mut self) -> &mut ::std::string::String {
        &mut self.rl1
    }

    // Take field
    pub fn take_rl1(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.rl1, ::std::string::String::new())
    }

    // string rl2 = 33;


    pub fn get_rl2(&self) -> &str {
        &self.rl2
    }
    pub fn clear_rl2(&mut self) {
        self.rl2.clear();
    }

    // Param is passed by value, moved
    pub fn set_rl2(&mut self, v: ::std::string::String) {
        self.rl2 = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_rl2(&mut self) -> &mut ::std::string::String {
        &mut self.rl2
    }

    // Take field
    pub fn take_rl2(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.rl2, ::std::string::String::new())
    }

    // string rl3 = 34;


    pub fn get_rl3(&self) -> &str {
        &self.rl3
    }
    pub fn clear_rl3(&mut self) {
        self.rl3.clear();
    }

    // Param is passed by value, moved
    pub fn set_rl3(&mut self, v: ::std::string::String) {
        self.rl3 = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_rl3(&mut self) -> &mut ::std::string::String {
        &mut self.rl3
    }

    // Take field
    pub fn take_rl3(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.rl3, ::std::string::String::new())
    }

    // float calc_ftp_rate = 35;


    pub fn get_calc_ftp_rate(&self) -> f32 {
        self.calc_ftp_rate
    }
    pub fn clear_calc_ftp_rate(&mut self) {
        self.calc_ftp_rate = 0.;
    }

    // Param is passed by value, moved
    pub fn set_calc_ftp_rate(&mut self, v: f32) {
        self.calc_ftp_rate = v;
    }

    // float calc_lock_spread = 36;


    pub fn get_calc_lock_spread(&self) -> f32 {
        self.calc_lock_spread
    }
    pub fn clear_calc_lock_spread(&mut self) {
        self.calc_lock_spread = 0.;
    }

    // Param is passed by value, moved
    pub fn set_calc_lock_spread(&mut self, v: f32) {
        self.calc_lock_spread = v;
    }

    // int64 bc_as_on_rule = 37;


    pub fn get_bc_as_on_rule(&self) -> i64 {
        self.bc_as_on_rule
    }
    pub fn clear_bc_as_on_rule(&mut self) {
        self.bc_as_on_rule = 0;
    }

    // Param is passed by value, moved
    pub fn set_bc_as_on_rule(&mut self, v: i64) {
        self.bc_as_on_rule = v;
    }

    // int64 tenor_start_date_rule = 38;


    pub fn get_tenor_start_date_rule(&self) -> i64 {
        self.tenor_start_date_rule
    }
    pub fn clear_tenor_start_date_rule(&mut self) {
        self.tenor_start_date_rule = 0;
    }

    // Param is passed by value, moved
    pub fn set_tenor_start_date_rule(&mut self, v: i64) {
        self.tenor_start_date_rule = v;
    }

    // int64 tenor_end_date_rule = 39;


    pub fn get_tenor_end_date_rule(&self) -> i64 {
        self.tenor_end_date_rule
    }
    pub fn clear_tenor_end_date_rule(&mut self) {
        self.tenor_end_date_rule = 0;
    }

    // Param is passed by value, moved
    pub fn set_tenor_end_date_rule(&mut self, v: i64) {
        self.tenor_end_date_rule = v;
    }

    // int64 bc_as_on_applied = 40;


    pub fn get_bc_as_on_applied(&self) -> i64 {
        self.bc_as_on_applied
    }
    pub fn clear_bc_as_on_applied(&mut self) {
        self.bc_as_on_applied = 0;
    }

    // Param is passed by value, moved
    pub fn set_bc_as_on_applied(&mut self, v: i64) {
        self.bc_as_on_applied = v;
    }

    // int64 tenor_start_date_applied = 41;


    pub fn get_tenor_start_date_applied(&self) -> i64 {
        self.tenor_start_date_applied
    }
    pub fn clear_tenor_start_date_applied(&mut self) {
        self.tenor_start_date_applied = 0;
    }

    // Param is passed by value, moved
    pub fn set_tenor_start_date_applied(&mut self, v: i64) {
        self.tenor_start_date_applied = v;
    }

    // int64 tenor_end_date_applied = 42;


    pub fn get_tenor_end_date_applied(&self) -> i64 {
        self.tenor_end_date_applied
    }
    pub fn clear_tenor_end_date_applied(&mut self) {
        self.tenor_end_date_applied = 0;
    }

    // Param is passed by value, moved
    pub fn set_tenor_end_date_applied(&mut self, v: i64) {
        self.tenor_end_date_applied = v;
    }

    // string gl_code = 43;


    pub fn get_gl_code(&self) -> &str {
        &self.gl_code
    }
    pub fn clear_gl_code(&mut self) {
        self.gl_code.clear();
    }

    // Param is passed by value, moved
    pub fn set_gl_code(&mut self, v: ::std::string::String) {
        self.gl_code = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_gl_code(&mut self) -> &mut ::std::string::String {
        &mut self.gl_code
    }

    // Take field
    pub fn take_gl_code(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.gl_code, ::std::string::String::new())
    }

    // string prod_code = 44;


    pub fn get_prod_code(&self) -> &str {
        &self.prod_code
    }
    pub fn clear_prod_code(&mut self) {
        self.prod_code.clear();
    }

    // Param is passed by value, moved
    pub fn set_prod_code(&mut self, v: ::std::string::String) {
        self.prod_code = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_prod_code(&mut self) -> &mut ::std::string::String {
        &mut self.prod_code
    }

    // Take field
    pub fn take_prod_code(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.prod_code, ::std::string::String::new())
    }

    // string div_code = 45;


    pub fn get_div_code(&self) -> &str {
        &self.div_code
    }
    pub fn clear_div_code(&mut self) {
        self.div_code.clear();
    }

    // Param is passed by value, moved
    pub fn set_div_code(&mut self, v: ::std::string::String) {
        self.div_code = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_div_code(&mut self) -> &mut ::std::string::String {
        &mut self.div_code
    }

    // Take field
    pub fn take_div_code(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.div_code, ::std::string::String::new())
    }

    // string mis_code_1 = 46;


    pub fn get_mis_code_1(&self) -> &str {
        &self.mis_code_1
    }
    pub fn clear_mis_code_1(&mut self) {
        self.mis_code_1.clear();
    }

    // Param is passed by value, moved
    pub fn set_mis_code_1(&mut self, v: ::std::string::String) {
        self.mis_code_1 = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_mis_code_1(&mut self) -> &mut ::std::string::String {
        &mut self.mis_code_1
    }

    // Take field
    pub fn take_mis_code_1(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.mis_code_1, ::std::string::String::new())
    }

    // string mis_code_2 = 47;


    pub fn get_mis_code_2(&self) -> &str {
        &self.mis_code_2
    }
    pub fn clear_mis_code_2(&mut self) {
        self.mis_code_2.clear();
    }

    // Param is passed by value, moved
    pub fn set_mis_code_2(&mut self, v: ::std::string::String) {
        self.mis_code_2 = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_mis_code_2(&mut self) -> &mut ::std::string::String {
        &mut self.mis_code_2
    }

    // Take field
    pub fn take_mis_code_2(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.mis_code_2, ::std::string::String::new())
    }

    // string mis_code_3 = 48;


    pub fn get_mis_code_3(&self) -> &str {
        &self.mis_code_3
    }
    pub fn clear_mis_code_3(&mut self) {
        self.mis_code_3.clear();
    }

    // Param is passed by value, moved
    pub fn set_mis_code_3(&mut self, v: ::std::string::String) {
        self.mis_code_3 = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_mis_code_3(&mut self) -> &mut ::std::string::String {
        &mut self.mis_code_3
    }

    // Take field
    pub fn take_mis_code_3(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.mis_code_3, ::std::string::String::new())
    }
}

impl ::protobuf::Message for OneAccountView {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int64()?;
                    self.as_on_month = tmp;
                },
                2 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.account_id)?;
                },
                3 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.currency)?;
                },
                4 => {
                    if wire_type != ::protobuf::wire_format::WireTypeFixed64 {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_double()?;
                    self.balance_ccy = tmp;
                },
                5 => {
                    if wire_type != ::protobuf::wire_format::WireTypeFixed64 {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_double()?;
                    self.balance_hcy = tmp;
                },
                6 => {
                    if wire_type != ::protobuf::wire_format::WireTypeFixed32 {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_float()?;
                    self.int_rate = tmp;
                },
                7 => {
                    if wire_type != ::protobuf::wire_format::WireTypeFixed64 {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_double()?;
                    self.acr_int_amt_ccy = tmp;
                },
                8 => {
                    if wire_type != ::protobuf::wire_format::WireTypeFixed64 {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_double()?;
                    self.acr_int_amt_hcy = tmp;
                },
                9 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.ftp_method)?;
                },
                10 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int32()?;
                    self.base_rate_curve_id = tmp;
                },
                11 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.rate_flag)?;
                },
                12 => {
                    ::protobuf::rt::read_repeated_int32_into(wire_type, is, &mut self.adj_codes)?;
                },
                13 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int64()?;
                    self.val_dt = tmp;
                },
                14 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int64()?;
                    self.open_dt = tmp;
                },
                15 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int64()?;
                    self.mat_dt = tmp;
                },
                16 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int64()?;
                    self.lst_repricing_dt = tmp;
                },
                17 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.rep_freq)?;
                },
                18 => {
                    if wire_type != ::protobuf::wire_format::WireTypeFixed64 {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_double()?;
                    self.cust_agg_bal = tmp;
                },
                19 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.day_count_basis)?;
                },
                20 => {
                    if wire_type != ::protobuf::wire_format::WireTypeFixed32 {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_float()?;
                    self.base_rate = tmp;
                },
                21 => {
                    ::protobuf::rt::read_repeated_float_into(wire_type, is, &mut self.adj_rates)?;
                },
                22 => {
                    if wire_type != ::protobuf::wire_format::WireTypeFixed32 {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_float()?;
                    self.ftp_rate = tmp;
                },
                23 => {
                    if wire_type != ::protobuf::wire_format::WireTypeFixed32 {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_float()?;
                    self.lock_spread = tmp;
                },
                24 => {
                    if wire_type != ::protobuf::wire_format::WireTypeFixed64 {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_double()?;
                    self.ftp_amt_ccy = tmp;
                },
                25 => {
                    if wire_type != ::protobuf::wire_format::WireTypeFixed64 {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_double()?;
                    self.ftp_amt_hcy = tmp;
                },
                26 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.a_or_l)?;
                },
                27 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.dim1)?;
                },
                28 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.dim2)?;
                },
                29 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.dim3)?;
                },
                30 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.dim4)?;
                },
                31 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.customer_id)?;
                },
                32 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.rl1)?;
                },
                33 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.rl2)?;
                },
                34 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.rl3)?;
                },
                35 => {
                    if wire_type != ::protobuf::wire_format::WireTypeFixed32 {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_float()?;
                    self.calc_ftp_rate = tmp;
                },
                36 => {
                    if wire_type != ::protobuf::wire_format::WireTypeFixed32 {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_float()?;
                    self.calc_lock_spread = tmp;
                },
                37 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int64()?;
                    self.bc_as_on_rule = tmp;
                },
                38 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int64()?;
                    self.tenor_start_date_rule = tmp;
                },
                39 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int64()?;
                    self.tenor_end_date_rule = tmp;
                },
                40 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int64()?;
                    self.bc_as_on_applied = tmp;
                },
                41 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int64()?;
                    self.tenor_start_date_applied = tmp;
                },
                42 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int64()?;
                    self.tenor_end_date_applied = tmp;
                },
                43 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.gl_code)?;
                },
                44 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.prod_code)?;
                },
                45 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.div_code)?;
                },
                46 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.mis_code_1)?;
                },
                47 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.mis_code_2)?;
                },
                48 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.mis_code_3)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.as_on_month != 0 {
            my_size += ::protobuf::rt::value_size(1, self.as_on_month, ::protobuf::wire_format::WireTypeVarint);
        }
        if !self.account_id.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.account_id);
        }
        if !self.currency.is_empty() {
            my_size += ::protobuf::rt::string_size(3, &self.currency);
        }
        if self.balance_ccy != 0. {
            my_size += 9;
        }
        if self.balance_hcy != 0. {
            my_size += 9;
        }
        if self.int_rate != 0. {
            my_size += 5;
        }
        if self.acr_int_amt_ccy != 0. {
            my_size += 9;
        }
        if self.acr_int_amt_hcy != 0. {
            my_size += 9;
        }
        if !self.ftp_method.is_empty() {
            my_size += ::protobuf::rt::string_size(9, &self.ftp_method);
        }
        if self.base_rate_curve_id != 0 {
            my_size += ::protobuf::rt::value_size(10, self.base_rate_curve_id, ::protobuf::wire_format::WireTypeVarint);
        }
        if !self.rate_flag.is_empty() {
            my_size += ::protobuf::rt::string_size(11, &self.rate_flag);
        }
        for value in &self.adj_codes {
            my_size += ::protobuf::rt::value_size(12, *value, ::protobuf::wire_format::WireTypeVarint);
        };
        if self.val_dt != 0 {
            my_size += ::protobuf::rt::value_size(13, self.val_dt, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.open_dt != 0 {
            my_size += ::protobuf::rt::value_size(14, self.open_dt, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.mat_dt != 0 {
            my_size += ::protobuf::rt::value_size(15, self.mat_dt, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.lst_repricing_dt != 0 {
            my_size += ::protobuf::rt::value_size(16, self.lst_repricing_dt, ::protobuf::wire_format::WireTypeVarint);
        }
        if !self.rep_freq.is_empty() {
            my_size += ::protobuf::rt::string_size(17, &self.rep_freq);
        }
        if self.cust_agg_bal != 0. {
            my_size += 10;
        }
        if !self.day_count_basis.is_empty() {
            my_size += ::protobuf::rt::string_size(19, &self.day_count_basis);
        }
        if self.base_rate != 0. {
            my_size += 6;
        }
        my_size += 6 * self.adj_rates.len() as u32;
        if self.ftp_rate != 0. {
            my_size += 6;
        }
        if self.lock_spread != 0. {
            my_size += 6;
        }
        if self.ftp_amt_ccy != 0. {
            my_size += 10;
        }
        if self.ftp_amt_hcy != 0. {
            my_size += 10;
        }
        if !self.a_or_l.is_empty() {
            my_size += ::protobuf::rt::string_size(26, &self.a_or_l);
        }
        if !self.dim1.is_empty() {
            my_size += ::protobuf::rt::string_size(27, &self.dim1);
        }
        if !self.dim2.is_empty() {
            my_size += ::protobuf::rt::string_size(28, &self.dim2);
        }
        if !self.dim3.is_empty() {
            my_size += ::protobuf::rt::string_size(29, &self.dim3);
        }
        if !self.dim4.is_empty() {
            my_size += ::protobuf::rt::string_size(30, &self.dim4);
        }
        if !self.customer_id.is_empty() {
            my_size += ::protobuf::rt::string_size(31, &self.customer_id);
        }
        if !self.rl1.is_empty() {
            my_size += ::protobuf::rt::string_size(32, &self.rl1);
        }
        if !self.rl2.is_empty() {
            my_size += ::protobuf::rt::string_size(33, &self.rl2);
        }
        if !self.rl3.is_empty() {
            my_size += ::protobuf::rt::string_size(34, &self.rl3);
        }
        if self.calc_ftp_rate != 0. {
            my_size += 6;
        }
        if self.calc_lock_spread != 0. {
            my_size += 6;
        }
        if self.bc_as_on_rule != 0 {
            my_size += ::protobuf::rt::value_size(37, self.bc_as_on_rule, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.tenor_start_date_rule != 0 {
            my_size += ::protobuf::rt::value_size(38, self.tenor_start_date_rule, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.tenor_end_date_rule != 0 {
            my_size += ::protobuf::rt::value_size(39, self.tenor_end_date_rule, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.bc_as_on_applied != 0 {
            my_size += ::protobuf::rt::value_size(40, self.bc_as_on_applied, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.tenor_start_date_applied != 0 {
            my_size += ::protobuf::rt::value_size(41, self.tenor_start_date_applied, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.tenor_end_date_applied != 0 {
            my_size += ::protobuf::rt::value_size(42, self.tenor_end_date_applied, ::protobuf::wire_format::WireTypeVarint);
        }
        if !self.gl_code.is_empty() {
            my_size += ::protobuf::rt::string_size(43, &self.gl_code);
        }
        if !self.prod_code.is_empty() {
            my_size += ::protobuf::rt::string_size(44, &self.prod_code);
        }
        if !self.div_code.is_empty() {
            my_size += ::protobuf::rt::string_size(45, &self.div_code);
        }
        if !self.mis_code_1.is_empty() {
            my_size += ::protobuf::rt::string_size(46, &self.mis_code_1);
        }
        if !self.mis_code_2.is_empty() {
            my_size += ::protobuf::rt::string_size(47, &self.mis_code_2);
        }
        if !self.mis_code_3.is_empty() {
            my_size += ::protobuf::rt::string_size(48, &self.mis_code_3);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if self.as_on_month != 0 {
            os.write_int64(1, self.as_on_month)?;
        }
        if !self.account_id.is_empty() {
            os.write_string(2, &self.account_id)?;
        }
        if !self.currency.is_empty() {
            os.write_string(3, &self.currency)?;
        }
        if self.balance_ccy != 0. {
            os.write_double(4, self.balance_ccy)?;
        }
        if self.balance_hcy != 0. {
            os.write_double(5, self.balance_hcy)?;
        }
        if self.int_rate != 0. {
            os.write_float(6, self.int_rate)?;
        }
        if self.acr_int_amt_ccy != 0. {
            os.write_double(7, self.acr_int_amt_ccy)?;
        }
        if self.acr_int_amt_hcy != 0. {
            os.write_double(8, self.acr_int_amt_hcy)?;
        }
        if !self.ftp_method.is_empty() {
            os.write_string(9, &self.ftp_method)?;
        }
        if self.base_rate_curve_id != 0 {
            os.write_int32(10, self.base_rate_curve_id)?;
        }
        if !self.rate_flag.is_empty() {
            os.write_string(11, &self.rate_flag)?;
        }
        for v in &self.adj_codes {
            os.write_int32(12, *v)?;
        };
        if self.val_dt != 0 {
            os.write_int64(13, self.val_dt)?;
        }
        if self.open_dt != 0 {
            os.write_int64(14, self.open_dt)?;
        }
        if self.mat_dt != 0 {
            os.write_int64(15, self.mat_dt)?;
        }
        if self.lst_repricing_dt != 0 {
            os.write_int64(16, self.lst_repricing_dt)?;
        }
        if !self.rep_freq.is_empty() {
            os.write_string(17, &self.rep_freq)?;
        }
        if self.cust_agg_bal != 0. {
            os.write_double(18, self.cust_agg_bal)?;
        }
        if !self.day_count_basis.is_empty() {
            os.write_string(19, &self.day_count_basis)?;
        }
        if self.base_rate != 0. {
            os.write_float(20, self.base_rate)?;
        }
        for v in &self.adj_rates {
            os.write_float(21, *v)?;
        };
        if self.ftp_rate != 0. {
            os.write_float(22, self.ftp_rate)?;
        }
        if self.lock_spread != 0. {
            os.write_float(23, self.lock_spread)?;
        }
        if self.ftp_amt_ccy != 0. {
            os.write_double(24, self.ftp_amt_ccy)?;
        }
        if self.ftp_amt_hcy != 0. {
            os.write_double(25, self.ftp_amt_hcy)?;
        }
        if !self.a_or_l.is_empty() {
            os.write_string(26, &self.a_or_l)?;
        }
        if !self.dim1.is_empty() {
            os.write_string(27, &self.dim1)?;
        }
        if !self.dim2.is_empty() {
            os.write_string(28, &self.dim2)?;
        }
        if !self.dim3.is_empty() {
            os.write_string(29, &self.dim3)?;
        }
        if !self.dim4.is_empty() {
            os.write_string(30, &self.dim4)?;
        }
        if !self.customer_id.is_empty() {
            os.write_string(31, &self.customer_id)?;
        }
        if !self.rl1.is_empty() {
            os.write_string(32, &self.rl1)?;
        }
        if !self.rl2.is_empty() {
            os.write_string(33, &self.rl2)?;
        }
        if !self.rl3.is_empty() {
            os.write_string(34, &self.rl3)?;
        }
        if self.calc_ftp_rate != 0. {
            os.write_float(35, self.calc_ftp_rate)?;
        }
        if self.calc_lock_spread != 0. {
            os.write_float(36, self.calc_lock_spread)?;
        }
        if self.bc_as_on_rule != 0 {
            os.write_int64(37, self.bc_as_on_rule)?;
        }
        if self.tenor_start_date_rule != 0 {
            os.write_int64(38, self.tenor_start_date_rule)?;
        }
        if self.tenor_end_date_rule != 0 {
            os.write_int64(39, self.tenor_end_date_rule)?;
        }
        if self.bc_as_on_applied != 0 {
            os.write_int64(40, self.bc_as_on_applied)?;
        }
        if self.tenor_start_date_applied != 0 {
            os.write_int64(41, self.tenor_start_date_applied)?;
        }
        if self.tenor_end_date_applied != 0 {
            os.write_int64(42, self.tenor_end_date_applied)?;
        }
        if !self.gl_code.is_empty() {
            os.write_string(43, &self.gl_code)?;
        }
        if !self.prod_code.is_empty() {
            os.write_string(44, &self.prod_code)?;
        }
        if !self.div_code.is_empty() {
            os.write_string(45, &self.div_code)?;
        }
        if !self.mis_code_1.is_empty() {
            os.write_string(46, &self.mis_code_1)?;
        }
        if !self.mis_code_2.is_empty() {
            os.write_string(47, &self.mis_code_2)?;
        }
        if !self.mis_code_3.is_empty() {
            os.write_string(48, &self.mis_code_3)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> OneAccountView {
        OneAccountView::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy::INIT;
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt64>(
                    "as_on_month",
                    |m: &OneAccountView| { &m.as_on_month },
                    |m: &mut OneAccountView| { &mut m.as_on_month },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "account_id",
                    |m: &OneAccountView| { &m.account_id },
                    |m: &mut OneAccountView| { &mut m.account_id },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "currency",
                    |m: &OneAccountView| { &m.currency },
                    |m: &mut OneAccountView| { &mut m.currency },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeDouble>(
                    "balance_ccy",
                    |m: &OneAccountView| { &m.balance_ccy },
                    |m: &mut OneAccountView| { &mut m.balance_ccy },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeDouble>(
                    "balance_hcy",
                    |m: &OneAccountView| { &m.balance_hcy },
                    |m: &mut OneAccountView| { &mut m.balance_hcy },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeFloat>(
                    "int_rate",
                    |m: &OneAccountView| { &m.int_rate },
                    |m: &mut OneAccountView| { &mut m.int_rate },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeDouble>(
                    "acr_int_amt_ccy",
                    |m: &OneAccountView| { &m.acr_int_amt_ccy },
                    |m: &mut OneAccountView| { &mut m.acr_int_amt_ccy },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeDouble>(
                    "acr_int_amt_hcy",
                    |m: &OneAccountView| { &m.acr_int_amt_hcy },
                    |m: &mut OneAccountView| { &mut m.acr_int_amt_hcy },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "ftp_method",
                    |m: &OneAccountView| { &m.ftp_method },
                    |m: &mut OneAccountView| { &mut m.ftp_method },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt32>(
                    "base_rate_curve_id",
                    |m: &OneAccountView| { &m.base_rate_curve_id },
                    |m: &mut OneAccountView| { &mut m.base_rate_curve_id },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "rate_flag",
                    |m: &OneAccountView| { &m.rate_flag },
                    |m: &mut OneAccountView| { &mut m.rate_flag },
                ));
                fields.push(::protobuf::reflect::accessor::make_vec_accessor::<_, ::protobuf::types::ProtobufTypeInt32>(
                    "adj_codes",
                    |m: &OneAccountView| { &m.adj_codes },
                    |m: &mut OneAccountView| { &mut m.adj_codes },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt64>(
                    "val_dt",
                    |m: &OneAccountView| { &m.val_dt },
                    |m: &mut OneAccountView| { &mut m.val_dt },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt64>(
                    "open_dt",
                    |m: &OneAccountView| { &m.open_dt },
                    |m: &mut OneAccountView| { &mut m.open_dt },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt64>(
                    "mat_dt",
                    |m: &OneAccountView| { &m.mat_dt },
                    |m: &mut OneAccountView| { &mut m.mat_dt },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt64>(
                    "lst_repricing_dt",
                    |m: &OneAccountView| { &m.lst_repricing_dt },
                    |m: &mut OneAccountView| { &mut m.lst_repricing_dt },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "rep_freq",
                    |m: &OneAccountView| { &m.rep_freq },
                    |m: &mut OneAccountView| { &mut m.rep_freq },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeDouble>(
                    "cust_agg_bal",
                    |m: &OneAccountView| { &m.cust_agg_bal },
                    |m: &mut OneAccountView| { &mut m.cust_agg_bal },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "day_count_basis",
                    |m: &OneAccountView| { &m.day_count_basis },
                    |m: &mut OneAccountView| { &mut m.day_count_basis },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeFloat>(
                    "base_rate",
                    |m: &OneAccountView| { &m.base_rate },
                    |m: &mut OneAccountView| { &mut m.base_rate },
                ));
                fields.push(::protobuf::reflect::accessor::make_vec_accessor::<_, ::protobuf::types::ProtobufTypeFloat>(
                    "adj_rates",
                    |m: &OneAccountView| { &m.adj_rates },
                    |m: &mut OneAccountView| { &mut m.adj_rates },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeFloat>(
                    "ftp_rate",
                    |m: &OneAccountView| { &m.ftp_rate },
                    |m: &mut OneAccountView| { &mut m.ftp_rate },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeFloat>(
                    "lock_spread",
                    |m: &OneAccountView| { &m.lock_spread },
                    |m: &mut OneAccountView| { &mut m.lock_spread },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeDouble>(
                    "ftp_amt_ccy",
                    |m: &OneAccountView| { &m.ftp_amt_ccy },
                    |m: &mut OneAccountView| { &mut m.ftp_amt_ccy },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeDouble>(
                    "ftp_amt_hcy",
                    |m: &OneAccountView| { &m.ftp_amt_hcy },
                    |m: &mut OneAccountView| { &mut m.ftp_amt_hcy },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "a_or_l",
                    |m: &OneAccountView| { &m.a_or_l },
                    |m: &mut OneAccountView| { &mut m.a_or_l },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "dim1",
                    |m: &OneAccountView| { &m.dim1 },
                    |m: &mut OneAccountView| { &mut m.dim1 },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "dim2",
                    |m: &OneAccountView| { &m.dim2 },
                    |m: &mut OneAccountView| { &mut m.dim2 },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "dim3",
                    |m: &OneAccountView| { &m.dim3 },
                    |m: &mut OneAccountView| { &mut m.dim3 },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "dim4",
                    |m: &OneAccountView| { &m.dim4 },
                    |m: &mut OneAccountView| { &mut m.dim4 },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "customer_id",
                    |m: &OneAccountView| { &m.customer_id },
                    |m: &mut OneAccountView| { &mut m.customer_id },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "rl1",
                    |m: &OneAccountView| { &m.rl1 },
                    |m: &mut OneAccountView| { &mut m.rl1 },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "rl2",
                    |m: &OneAccountView| { &m.rl2 },
                    |m: &mut OneAccountView| { &mut m.rl2 },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "rl3",
                    |m: &OneAccountView| { &m.rl3 },
                    |m: &mut OneAccountView| { &mut m.rl3 },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeFloat>(
                    "calc_ftp_rate",
                    |m: &OneAccountView| { &m.calc_ftp_rate },
                    |m: &mut OneAccountView| { &mut m.calc_ftp_rate },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeFloat>(
                    "calc_lock_spread",
                    |m: &OneAccountView| { &m.calc_lock_spread },
                    |m: &mut OneAccountView| { &mut m.calc_lock_spread },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt64>(
                    "bc_as_on_rule",
                    |m: &OneAccountView| { &m.bc_as_on_rule },
                    |m: &mut OneAccountView| { &mut m.bc_as_on_rule },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt64>(
                    "tenor_start_date_rule",
                    |m: &OneAccountView| { &m.tenor_start_date_rule },
                    |m: &mut OneAccountView| { &mut m.tenor_start_date_rule },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt64>(
                    "tenor_end_date_rule",
                    |m: &OneAccountView| { &m.tenor_end_date_rule },
                    |m: &mut OneAccountView| { &mut m.tenor_end_date_rule },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt64>(
                    "bc_as_on_applied",
                    |m: &OneAccountView| { &m.bc_as_on_applied },
                    |m: &mut OneAccountView| { &mut m.bc_as_on_applied },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt64>(
                    "tenor_start_date_applied",
                    |m: &OneAccountView| { &m.tenor_start_date_applied },
                    |m: &mut OneAccountView| { &mut m.tenor_start_date_applied },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt64>(
                    "tenor_end_date_applied",
                    |m: &OneAccountView| { &m.tenor_end_date_applied },
                    |m: &mut OneAccountView| { &mut m.tenor_end_date_applied },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "gl_code",
                    |m: &OneAccountView| { &m.gl_code },
                    |m: &mut OneAccountView| { &mut m.gl_code },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "prod_code",
                    |m: &OneAccountView| { &m.prod_code },
                    |m: &mut OneAccountView| { &mut m.prod_code },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "div_code",
                    |m: &OneAccountView| { &m.div_code },
                    |m: &mut OneAccountView| { &mut m.div_code },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "mis_code_1",
                    |m: &OneAccountView| { &m.mis_code_1 },
                    |m: &mut OneAccountView| { &mut m.mis_code_1 },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "mis_code_2",
                    |m: &OneAccountView| { &m.mis_code_2 },
                    |m: &mut OneAccountView| { &mut m.mis_code_2 },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "mis_code_3",
                    |m: &OneAccountView| { &m.mis_code_3 },
                    |m: &mut OneAccountView| { &mut m.mis_code_3 },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<OneAccountView>(
                    "OneAccountView",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static OneAccountView {
        static mut instance: ::protobuf::lazy::Lazy<OneAccountView> = ::protobuf::lazy::Lazy::INIT;
        unsafe {
            instance.get(OneAccountView::new)
        }
    }
}

impl ::protobuf::Clear for OneAccountView {
    fn clear(&mut self) {
        self.as_on_month = 0;
        self.account_id.clear();
        self.currency.clear();
        self.balance_ccy = 0.;
        self.balance_hcy = 0.;
        self.int_rate = 0.;
        self.acr_int_amt_ccy = 0.;
        self.acr_int_amt_hcy = 0.;
        self.ftp_method.clear();
        self.base_rate_curve_id = 0;
        self.rate_flag.clear();
        self.adj_codes.clear();
        self.val_dt = 0;
        self.open_dt = 0;
        self.mat_dt = 0;
        self.lst_repricing_dt = 0;
        self.rep_freq.clear();
        self.cust_agg_bal = 0.;
        self.day_count_basis.clear();
        self.base_rate = 0.;
        self.adj_rates.clear();
        self.ftp_rate = 0.;
        self.lock_spread = 0.;
        self.ftp_amt_ccy = 0.;
        self.ftp_amt_hcy = 0.;
        self.a_or_l.clear();
        self.dim1.clear();
        self.dim2.clear();
        self.dim3.clear();
        self.dim4.clear();
        self.customer_id.clear();
        self.rl1.clear();
        self.rl2.clear();
        self.rl3.clear();
        self.calc_ftp_rate = 0.;
        self.calc_lock_spread = 0.;
        self.bc_as_on_rule = 0;
        self.tenor_start_date_rule = 0;
        self.tenor_end_date_rule = 0;
        self.bc_as_on_applied = 0;
        self.tenor_start_date_applied = 0;
        self.tenor_end_date_applied = 0;
        self.gl_code.clear();
        self.prod_code.clear();
        self.div_code.clear();
        self.mis_code_1.clear();
        self.mis_code_2.clear();
        self.mis_code_3.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for OneAccountView {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for OneAccountView {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x16one_acc_smry_rep.proto\"\xfa\x0b\n\x0eOneAccountView\x12\x1e\n\x0b\
    as_on_month\x18\x01\x20\x01(\x03R\tasOnMonth\x12\x1d\n\naccount_id\x18\
    \x02\x20\x01(\tR\taccountId\x12\x1a\n\x08currency\x18\x03\x20\x01(\tR\
    \x08currency\x12\x1f\n\x0bbalance_ccy\x18\x04\x20\x01(\x01R\nbalanceCcy\
    \x12\x1f\n\x0bbalance_hcy\x18\x05\x20\x01(\x01R\nbalanceHcy\x12\x19\n\
    \x08int_rate\x18\x06\x20\x01(\x02R\x07intRate\x12%\n\x0facr_int_amt_ccy\
    \x18\x07\x20\x01(\x01R\x0cacrIntAmtCcy\x12%\n\x0facr_int_amt_hcy\x18\x08\
    \x20\x01(\x01R\x0cacrIntAmtHcy\x12\x1d\n\nftp_method\x18\t\x20\x01(\tR\t\
    ftpMethod\x12+\n\x12base_rate_curve_id\x18\n\x20\x01(\x05R\x0fbaseRateCu\
    rveId\x12\x1b\n\trate_flag\x18\x0b\x20\x01(\tR\x08rateFlag\x12\x1b\n\tad\
    j_codes\x18\x0c\x20\x03(\x05R\x08adjCodes\x12\x15\n\x06val_dt\x18\r\x20\
    \x01(\x03R\x05valDt\x12\x17\n\x07open_dt\x18\x0e\x20\x01(\x03R\x06openDt\
    \x12\x15\n\x06mat_dt\x18\x0f\x20\x01(\x03R\x05matDt\x12(\n\x10lst_repric\
    ing_dt\x18\x10\x20\x01(\x03R\x0elstRepricingDt\x12\x19\n\x08rep_freq\x18\
    \x11\x20\x01(\tR\x07repFreq\x12\x20\n\x0ccust_agg_bal\x18\x12\x20\x01(\
    \x01R\ncustAggBal\x12&\n\x0fday_count_basis\x18\x13\x20\x01(\tR\rdayCoun\
    tBasis\x12\x1b\n\tbase_rate\x18\x14\x20\x01(\x02R\x08baseRate\x12\x1b\n\
    \tadj_rates\x18\x15\x20\x03(\x02R\x08adjRates\x12\x19\n\x08ftp_rate\x18\
    \x16\x20\x01(\x02R\x07ftpRate\x12\x1f\n\x0block_spread\x18\x17\x20\x01(\
    \x02R\nlockSpread\x12\x1e\n\x0bftp_amt_ccy\x18\x18\x20\x01(\x01R\tftpAmt\
    Ccy\x12\x1e\n\x0bftp_amt_hcy\x18\x19\x20\x01(\x01R\tftpAmtHcy\x12\x14\n\
    \x06a_or_l\x18\x1a\x20\x01(\tR\x04aOrL\x12\x12\n\x04dim1\x18\x1b\x20\x01\
    (\tR\x04dim1\x12\x12\n\x04dim2\x18\x1c\x20\x01(\tR\x04dim2\x12\x12\n\x04\
    dim3\x18\x1d\x20\x01(\tR\x04dim3\x12\x12\n\x04dim4\x18\x1e\x20\x01(\tR\
    \x04dim4\x12\x1f\n\x0bcustomer_id\x18\x1f\x20\x01(\tR\ncustomerId\x12\
    \x10\n\x03rl1\x18\x20\x20\x01(\tR\x03rl1\x12\x10\n\x03rl2\x18!\x20\x01(\
    \tR\x03rl2\x12\x10\n\x03rl3\x18\"\x20\x01(\tR\x03rl3\x12\"\n\rcalc_ftp_r\
    ate\x18#\x20\x01(\x02R\x0bcalcFtpRate\x12(\n\x10calc_lock_spread\x18$\
    \x20\x01(\x02R\x0ecalcLockSpread\x12!\n\rbc_as_on_rule\x18%\x20\x01(\x03\
    R\nbcAsOnRule\x121\n\x15tenor_start_date_rule\x18&\x20\x01(\x03R\x12teno\
    rStartDateRule\x12-\n\x13tenor_end_date_rule\x18'\x20\x01(\x03R\x10tenor\
    EndDateRule\x12'\n\x10bc_as_on_applied\x18(\x20\x01(\x03R\rbcAsOnApplied\
    \x127\n\x18tenor_start_date_applied\x18)\x20\x01(\x03R\x15tenorStartDate\
    Applied\x123\n\x16tenor_end_date_applied\x18*\x20\x01(\x03R\x13tenorEndD\
    ateApplied\x12\x17\n\x07gl_code\x18+\x20\x01(\tR\x06glCode\x12\x1b\n\tpr\
    od_code\x18,\x20\x01(\tR\x08prodCode\x12\x19\n\x08div_code\x18-\x20\x01(\
    \tR\x07divCode\x12\x1c\n\nmis_code_1\x18.\x20\x01(\tR\x08misCode1\x12\
    \x1c\n\nmis_code_2\x18/\x20\x01(\tR\x08misCode2\x12\x1c\n\nmis_code_3\
    \x180\x20\x01(\tR\x08misCode3b\x06proto3\
";

static mut file_descriptor_proto_lazy: ::protobuf::lazy::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::lazy::Lazy::INIT;

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    unsafe {
        file_descriptor_proto_lazy.get(|| {
            parse_descriptor_proto()
        })
    }
}
